services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis/redis-stack
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
  celery_worker:
    container_name: celery_worker
    build: .
    command:
      - celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - ecommerce_api/
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - api
      - redis
  flower:
    container_name: flower
    build: .
    command:
      - celery -A celery_worker celery flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - api
      - redis
      - celery_worker

